<?php
/**
 * ChannelsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Unifysell\SDK;

use Unifysell\SDK\Configuration;
use Unifysell\SDK\ApiException;
use Unifysell\SDK\ObjectSerializer;

/**
 * ChannelsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ChannelsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createChannel
     *
     * create a new channel.
     *
     */
    public function testCreateChannel()
    {
    }

    /**
     * Test case for createChannelV1
     *
     * create a new channel.
     *
     */
    public function testCreateChannelV1()
    {
    }

    /**
     * Test case for getChannel
     *
     * Show channel.
     *
     */
    public function testGetChannel()
    {
    }

    /**
     * Test case for getChannelV1
     *
     * Show channel.
     *
     */
    public function testGetChannelV1()
    {
    }

    /**
     * Test case for listChannels
     *
     * List channels.
     *
     */
    public function testListChannels()
    {
    }

    /**
     * Test case for listChannelsV1
     *
     * List channels.
     *
     */
    public function testListChannelsV1()
    {
    }

    /**
     * Test case for updateChannel
     *
     * update a channel.
     *
     */
    public function testUpdateChannel()
    {
    }

    /**
     * Test case for updateChannelV1
     *
     * update a channel.
     *
     */
    public function testUpdateChannelV1()
    {
    }
}
