<?php
/**
 * ListingsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Unifysell\SDK;

use \Unifysell\SDK\Configuration;
use \Unifysell\SDK\ApiException;
use \Unifysell\SDK\ObjectSerializer;

/**
 * ListingsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ListingsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createListing
     *
     * create a new listing.
     *
     */
    public function testCreateListing()
    {
    }

    /**
     * Test case for createListingV1
     *
     * create a new listing.
     *
     */
    public function testCreateListingV1()
    {
    }

    /**
     * Test case for getListing
     *
     * Show listing.
     *
     */
    public function testGetListing()
    {
    }

    /**
     * Test case for getListingV1
     *
     * Show listing.
     *
     */
    public function testGetListingV1()
    {
    }

    /**
     * Test case for listListings
     *
     * List listings.
     *
     */
    public function testListListings()
    {
    }

    /**
     * Test case for listListingsV1
     *
     * List listings.
     *
     */
    public function testListListingsV1()
    {
    }

    /**
     * Test case for updateListing
     *
     * update a listing.
     *
     */
    public function testUpdateListing()
    {
    }

    /**
     * Test case for updateListingV1
     *
     * update a listing.
     *
     */
    public function testUpdateListingV1()
    {
    }
}
