<?php
/**
 * MarketplacesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Unifysell\SDK;

use \Unifysell\SDK\Configuration;
use \Unifysell\SDK\ApiException;
use \Unifysell\SDK\ObjectSerializer;

/**
 * MarketplacesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MarketplacesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMarketplace
     *
     * create a new marketplace.
     *
     */
    public function testCreateMarketplace()
    {
    }

    /**
     * Test case for createMarketplaceV1
     *
     * create a new marketplace.
     *
     */
    public function testCreateMarketplaceV1()
    {
    }

    /**
     * Test case for getMarketplace
     *
     * Show marketplace.
     *
     */
    public function testGetMarketplace()
    {
    }

    /**
     * Test case for getMarketplaceV1
     *
     * Show marketplace.
     *
     */
    public function testGetMarketplaceV1()
    {
    }

    /**
     * Test case for listMarketplaces
     *
     * List marketplaces.
     *
     */
    public function testListMarketplaces()
    {
    }

    /**
     * Test case for listMarketplacesV1
     *
     * List marketplaces.
     *
     */
    public function testListMarketplacesV1()
    {
    }

    /**
     * Test case for updateMarketplace
     *
     * update a marketplace.
     *
     */
    public function testUpdateMarketplace()
    {
    }

    /**
     * Test case for updateMarketplaceV1
     *
     * update a marketplace.
     *
     */
    public function testUpdateMarketplaceV1()
    {
    }
}
