<?php
/**
 * PaymentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Unifysell\SDK;

use Unifysell\SDK\Configuration;
use Unifysell\SDK\ApiException;
use Unifysell\SDK\ObjectSerializer;

/**
 * PaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PaymentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getPaymentV1
     *
     * Show payment.
     *
     */
    public function testGetPaymentV1()
    {
    }

    /**
     * Test case for getPaymentV1_0
     *
     * Show payment.
     *
     */
    public function testGetPaymentV10()
    {
    }

    /**
     * Test case for getPaymentV1_1
     *
     * Show payment.
     *
     */
    public function testGetPaymentV11()
    {
    }

    /**
     * Test case for listPaymentsV0
     *
     * List payments.
     *
     */
    public function testListPaymentsV0()
    {
    }

    /**
     * Test case for listPaymentsV1
     *
     * List payments.
     *
     */
    public function testListPaymentsV1()
    {
    }

    /**
     * Test case for listPaymentsV1_0
     *
     * List payments.
     *
     */
    public function testListPaymentsV10()
    {
    }
}
