<?php
/**
 * TasksApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Unifysell\SDK;

use \Unifysell\SDK\Configuration;
use \Unifysell\SDK\ApiException;
use \Unifysell\SDK\ObjectSerializer;

/**
 * TasksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TasksApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getTask
     *
     * Show a task.
     *
     */
    public function testGetTask()
    {
    }

    /**
     * Test case for getTaskV0
     *
     * Show a task.
     *
     */
    public function testGetTaskV0()
    {
    }

    /**
     * Test case for getTaskV1
     *
     * Show a task.
     *
     */
    public function testGetTaskV1()
    {
    }

    /**
     * Test case for listTasks
     *
     * List my tasks.
     *
     */
    public function testListTasks()
    {
    }

    /**
     * Test case for listTasksV0
     *
     * List my tasks.
     *
     */
    public function testListTasksV0()
    {
    }

    /**
     * Test case for listTasksV1
     *
     * List my tasks.
     *
     */
    public function testListTasksV1()
    {
    }
}
