<?php
/**
 * ChannelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Unifysell\SDK;

/**
 * ChannelTest Class Doc Comment
 *
 * @category    Class
 * @description This describes a connection to any ecommerce platform.         E.g. Ebay or PayPal or DHL.         It therefor contains usernames, connection endpoints and secrets.
 * @package     Unifysell\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChannelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Channel"
     */
    public function testChannel()
    {
    }

    /**
     * Test attribute "date_changed"
     */
    public function testPropertyDateChanged()
    {
    }

    /**
     * Test attribute "partnership_password"
     */
    public function testPropertyPartnershipPassword()
    {
    }

    /**
     * Test attribute "shipment_marketplace_id"
     */
    public function testPropertyShipmentMarketplaceId()
    {
    }

    /**
     * Test attribute "account_password"
     */
    public function testPropertyAccountPassword()
    {
    }

    /**
     * Test attribute "api_url"
     */
    public function testPropertyApiUrl()
    {
    }

    /**
     * Test attribute "dev_key"
     */
    public function testPropertyDevKey()
    {
    }

    /**
     * Test attribute "attendance"
     */
    public function testPropertyAttendance()
    {
    }

    /**
     * Test attribute "access_key"
     */
    public function testPropertyAccessKey()
    {
    }

    /**
     * Test attribute "tracking_id"
     */
    public function testPropertyTrackingId()
    {
    }

    /**
     * Test attribute "channel_type"
     */
    public function testPropertyChannelType()
    {
    }

    /**
     * Test attribute "ekp_postfix"
     */
    public function testPropertyEkpPostfix()
    {
    }

    /**
     * Test attribute "prefer_bware"
     */
    public function testPropertyPreferBware()
    {
    }

    /**
     * Test attribute "is_payment_provider"
     */
    public function testPropertyIsPaymentProvider()
    {
    }

    /**
     * Test attribute "ekp_postfix_rules"
     */
    public function testPropertyEkpPostfixRules()
    {
    }

    /**
     * Test attribute "dev_password"
     */
    public function testPropertyDevPassword()
    {
    }

    /**
     * Test attribute "signature"
     */
    public function testPropertySignature()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "merchant_id"
     */
    public function testPropertyMerchantId()
    {
    }

    /**
     * Test attribute "url_sign_in"
     */
    public function testPropertyUrlSignIn()
    {
    }

    /**
     * Test attribute "is_shipment_provider"
     */
    public function testPropertyIsShipmentProvider()
    {
    }

    /**
     * Test attribute "app_password"
     */
    public function testPropertyAppPassword()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "service_url"
     */
    public function testPropertyServiceUrl()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "deleted"
     */
    public function testPropertyDeleted()
    {
    }

    /**
     * Test attribute "secret"
     */
    public function testPropertySecret()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "paypal_email_address"
     */
    public function testPropertyPaypalEmailAddress()
    {
    }

    /**
     * Test attribute "account_name"
     */
    public function testPropertyAccountName()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "dev_id"
     */
    public function testPropertyDevId()
    {
    }

    /**
     * Test attribute "outline_agreement"
     */
    public function testPropertyOutlineAgreement()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "url_finding"
     */
    public function testPropertyUrlFinding()
    {
    }

    /**
     * Test attribute "app_key"
     */
    public function testPropertyAppKey()
    {
    }

    /**
     * Test attribute "secret_key"
     */
    public function testPropertySecretKey()
    {
    }

    /**
     * Test attribute "marketplace_ids"
     */
    public function testPropertyMarketplaceIds()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "store_view"
     */
    public function testPropertyStoreView()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "is_sandbox"
     */
    public function testPropertyIsSandbox()
    {
    }

    /**
     * Test attribute "cert_id"
     */
    public function testPropertyCertId()
    {
    }

    /**
     * Test attribute "is_sales_provider"
     */
    public function testPropertyIsSalesProvider()
    {
    }

    /**
     * Test attribute "tracking_password"
     */
    public function testPropertyTrackingPassword()
    {
    }

    /**
     * Test attribute "channel_language"
     */
    public function testPropertyChannelLanguage()
    {
    }

    /**
     * Test attribute "api_password"
     */
    public function testPropertyApiPassword()
    {
    }

    /**
     * Test attribute "partnership_key"
     */
    public function testPropertyPartnershipKey()
    {
    }

    /**
     * Test attribute "ekp"
     */
    public function testPropertyEkp()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "api_username"
     */
    public function testPropertyApiUsername()
    {
    }

    /**
     * Test attribute "url_shopping"
     */
    public function testPropertyUrlShopping()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {
    }

    /**
     * Test attribute "merchant_channel_id"
     */
    public function testPropertyMerchantChannelId()
    {
    }

    /**
     * Test attribute "app_client_id"
     */
    public function testPropertyAppClientId()
    {
    }

    /**
     * Test attribute "credential"
     */
    public function testPropertyCredential()
    {
    }

    /**
     * Test attribute "username"
     */
    public function testPropertyUsername()
    {
    }

    /**
     * Test attribute "mws_auth_token"
     */
    public function testPropertyMwsAuthToken()
    {
    }

    /**
     * Test attribute "default_marketplace_id"
     */
    public function testPropertyDefaultMarketplaceId()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "marketplace_fallback_id"
     */
    public function testPropertyMarketplaceFallbackId()
    {
    }

    /**
     * Test attribute "url_trading"
     */
    public function testPropertyUrlTrading()
    {
    }
}
