<?php
/**
 * CreateListingRequestDeliveryOptionsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Unifysell\SDK;

/**
 * CreateListingRequestDeliveryOptionsTest Class Doc Comment
 *
 * @category    Class
 * @description CreateListingRequestDeliveryOptions
 * @package     Unifysell\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateListingRequestDeliveryOptionsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateListingRequestDeliveryOptions"
     */
    public function testCreateListingRequestDeliveryOptions()
    {
    }

    /**
     * Test attribute "shipping_is_cumulative"
     */
    public function testPropertyShippingIsCumulative()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "package_weight"
     */
    public function testPropertyPackageWeight()
    {
    }

    /**
     * Test attribute "package_size"
     */
    public function testPropertyPackageSize()
    {
    }

    /**
     * Test attribute "package_service"
     */
    public function testPropertyPackageService()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }
}
