<?php
/**
 * ListingTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Unifysell\SDK;

/**
 * ListingTest Class Doc Comment
 *
 * @category    Class */
// * @description Listing object schema.
/**
 * @package     Unifysell\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ListingTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Listing"
     */
    public function testListing()
    {
    }

    /**
     * Test attribute "article_current_price"
     */
    public function testPropertyArticleCurrentPrice()
    {
    }

    /**
     * Test attribute "article_id"
     */
    public function testPropertyArticleId()
    {
    }

    /**
     * Test attribute "asin"
     */
    public function testPropertyAsin()
    {
    }

    /**
     * Test attribute "asin1"
     */
    public function testPropertyAsin1()
    {
    }

    /**
     * Test attribute "asin2"
     */
    public function testPropertyAsin2()
    {
    }

    /**
     * Test attribute "asin3"
     */
    public function testPropertyAsin3()
    {
    }

    /**
     * Test attribute "auction_id"
     */
    public function testPropertyAuctionId()
    {
    }

    /**
     * Test attribute "auction_mode_id"
     */
    public function testPropertyAuctionModeId()
    {
    }

    /**
     * Test attribute "baseprice_unit"
     */
    public function testPropertyBasepriceUnit()
    {
    }

    /**
     * Test attribute "baseprice_volume"
     */
    public function testPropertyBasepriceVolume()
    {
    }

    /**
     * Test attribute "buy_now_price"
     */
    public function testPropertyBuyNowPrice()
    {
    }

    /**
     * Test attribute "category_ids"
     */
    public function testPropertyCategoryIds()
    {
    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {
    }

    /**
     * Test attribute "cross_selling_title"
     */
    public function testPropertyCrossSellingTitle()
    {
    }

    /**
     * Test attribute "date_changed"
     */
    public function testPropertyDateChanged()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "date_finished"
     */
    public function testPropertyDateFinished()
    {
    }

    /**
     * Test attribute "date_quantity_changed"
     */
    public function testPropertyDateQuantityChanged()
    {
    }

    /**
     * Test attribute "date_started"
     */
    public function testPropertyDateStarted()
    {
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "ean"
     */
    public function testPropertyEan()
    {
    }

    /**
     * Test attribute "ebay_item_id"
     */
    public function testPropertyEbayItemId()
    {
    }

    /**
     * Test attribute "has_variants"
     */
    public function testPropertyHasVariants()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "id_type"
     */
    public function testPropertyIdType()
    {
    }

    /**
     * Test attribute "inci"
     */
    public function testPropertyInci()
    {
    }

    /**
     * Test attribute "increment"
     */
    public function testPropertyIncrement()
    {
    }

    /**
     * Test attribute "is_available"
     */
    public function testPropertyIsAvailable()
    {
    }

    /**
     * Test attribute "is_closed"
     */
    public function testPropertyIsClosed()
    {
    }

    /**
     * Test attribute "is_connect"
     */
    public function testPropertyIsConnect()
    {
    }

    /**
     * Test attribute "is_planned"
     */
    public function testPropertyIsPlanned()
    {
    }

    /**
     * Test attribute "is_shown_on_homepage"
     */
    public function testPropertyIsShownOnHomepage()
    {
    }

    /**
     * Test attribute "is_stock_policed"
     */
    public function testPropertyIsStockPoliced()
    {
    }

    /**
     * Test attribute "is_visible"
     */
    public function testPropertyIsVisible()
    {
    }

    /**
     * Test attribute "isbn"
     */
    public function testPropertyIsbn()
    {
    }

    /**
     * Test attribute "language_id"
     */
    public function testPropertyLanguageId()
    {
    }

    /**
     * Test attribute "listing_id"
     */
    public function testPropertyListingId()
    {
    }

    /**
     * Test attribute "marketplace_id"
     */
    public function testPropertyMarketplaceId()
    {
    }

    /**
     * Test attribute "min_order_qty"
     */
    public function testPropertyMinOrderQty()
    {
    }

    /**
     * Test attribute "minimum_bid_price"
     */
    public function testPropertyMinimumBidPrice()
    {
    }

    /**
     * Test attribute "mpn"
     */
    public function testPropertyMpn()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "platform_sku"
     */
    public function testPropertyPlatformSku()
    {
    }

    /**
     * Test attribute "price"
     */
    public function testPropertyPrice()
    {
    }

    /**
     * Test attribute "price_reduced"
     */
    public function testPropertyPriceReduced()
    {
    }

    /**
     * Test attribute "price_reduced_type"
     */
    public function testPropertyPriceReducedType()
    {
    }

    /**
     * Test attribute "producer"
     */
    public function testPropertyProducer()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "qty_date"
     */
    public function testPropertyQtyDate()
    {
    }

    /**
     * Test attribute "qty_old"
     */
    public function testPropertyQtyOld()
    {
    }

    /**
     * Test attribute "qty_processed"
     */
    public function testPropertyQtyProcessed()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "rakuten_category_id"
     */
    public function testPropertyRakutenCategoryId()
    {
    }

    /**
     * Test attribute "seller_sku"
     */
    public function testPropertySellerSku()
    {
    }

    /**
     * Test attribute "set_id"
     */
    public function testPropertySetId()
    {
    }

    /**
     * Test attribute "shipping_group"
     */
    public function testPropertyShippingGroup()
    {
    }

    /**
     * Test attribute "shop_category_id"
     */
    public function testPropertyShopCategoryId()
    {
    }

    /**
     * Test attribute "staggering"
     */
    public function testPropertyStaggering()
    {
    }

    /**
     * Test attribute "start_price"
     */
    public function testPropertyStartPrice()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "tax"
     */
    public function testPropertyTax()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "upc"
     */
    public function testPropertyUpc()
    {
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
    }

    /**
     * Test attribute "url_marketing"
     */
    public function testPropertyUrlMarketing()
    {
    }

    /**
     * Test attribute "url_portal"
     */
    public function testPropertyUrlPortal()
    {
    }

    /**
     * Test attribute "url_shop"
     */
    public function testPropertyUrlShop()
    {
    }

    /**
     * Test attribute "watch_count"
     */
    public function testPropertyWatchCount()
    {
    }
}
