<?php
/**
 * MarketplaceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Unifysell\SDK;

/**
 * MarketplaceTest Class Doc Comment
 *
 * @category    Class */
// * @description Each marketplace exists in relation to a channel. It represents a subset of the channels market. On ebay and amazon for example a marketplace represents differnts countries markets. A platform also splits into separate marketplaces for selling, shipping and payment; e.g. on amazon. Some platforms like hood and rakuten don&#39;t have an internal marketplace representation. They still owe a single marketplace in the unifysell context. This is for generic purpose.
/**
 * @package     Unifysell\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarketplaceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Marketplace"
     */
    public function testMarketplace()
    {
    }

    /**
     * Test attribute "abbreviation"
     */
    public function testPropertyAbbreviation()
    {
    }

    /**
     * Test attribute "channel_id"
     */
    public function testPropertyChannelId()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {
    }

    /**
     * Test attribute "country_iso_code"
     */
    public function testPropertyCountryIsoCode()
    {
    }

    /**
     * Test attribute "date_changed"
     */
    public function testPropertyDateChanged()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "default_country_code"
     */
    public function testPropertyDefaultCountryCode()
    {
    }

    /**
     * Test attribute "default_currency_code"
     */
    public function testPropertyDefaultCurrencyCode()
    {
    }

    /**
     * Test attribute "default_language_code"
     */
    public function testPropertyDefaultLanguageCode()
    {
    }

    /**
     * Test attribute "domain_name"
     */
    public function testPropertyDomainName()
    {
    }

    /**
     * Test attribute "group_id"
     */
    public function testPropertyGroupId()
    {
    }

    /**
     * Test attribute "has_seller_suspended_listings"
     */
    public function testPropertyHasSellerSuspendedListings()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "marketplace_id"
     */
    public function testPropertyMarketplaceId()
    {
    }

    /**
     * Test attribute "marketplace_url"
     */
    public function testPropertyMarketplaceUrl()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {
    }

    /**
     * Test attribute "site"
     */
    public function testPropertySite()
    {
    }

    /**
     * Test attribute "site_id"
     */
    public function testPropertySiteId()
    {
    }

    /**
     * Test attribute "store_id"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "sync_activated"
     */
    public function testPropertySyncActivated()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "website_id"
     */
    public function testPropertyWebsiteId()
    {
    }
}
