<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.9
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Unifysell\SDK;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class
 * @description A unifysell order
 * @package     Unifysell\SDK
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {
    }

    /**
     * Test attribute "date_changed"
     */
    public function testPropertyDateChanged()
    {
    }

    /**
     * Test attribute "ebay_order_id"
     */
    public function testPropertyEbayOrderId()
    {
    }

    /**
     * Test attribute "order_type"
     */
    public function testPropertyOrderType()
    {
    }

    /**
     * Test attribute "is_premium_order"
     */
    public function testPropertyIsPremiumOrder()
    {
    }

    /**
     * Test attribute "ebay_payment_status"
     */
    public function testPropertyEbayPaymentStatus()
    {
    }

    /**
     * Test attribute "sales_channel"
     */
    public function testPropertySalesChannel()
    {
    }

    /**
     * Test attribute "package_service"
     */
    public function testPropertyPackageService()
    {
    }

    /**
     * Test attribute "amazon_order_id"
     */
    public function testPropertyAmazonOrderId()
    {
    }

    /**
     * Test attribute "shipped_by_amazon_tfm"
     */
    public function testPropertyShippedByAmazonTfm()
    {
    }

    /**
     * Test attribute "position_ids"
     */
    public function testPropertyPositionIds()
    {
    }

    /**
     * Test attribute "date_shipped"
     */
    public function testPropertyDateShipped()
    {
    }

    /**
     * Test attribute "invoice_no"
     */
    public function testPropertyInvoiceNo()
    {
    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {
    }

    /**
     * Test attribute "ship_method"
     */
    public function testPropertyShipMethod()
    {
    }

    /**
     * Test attribute "number_of_items_unshipped"
     */
    public function testPropertyNumberOfItemsUnshipped()
    {
    }

    /**
     * Test attribute "label_ids"
     */
    public function testPropertyLabelIds()
    {
    }

    /**
     * Test attribute "is_ebay_plus"
     */
    public function testPropertyIsEbayPlus()
    {
    }

    /**
     * Test attribute "fulfillment_channel"
     */
    public function testPropertyFulfillmentChannel()
    {
    }

    /**
     * Test attribute "hood_order_id"
     */
    public function testPropertyHoodOrderId()
    {
    }

    /**
     * Test attribute "ship_method_code"
     */
    public function testPropertyShipMethodCode()
    {
    }

    /**
     * Test attribute "remote_allowed_shipping_methods"
     */
    public function testPropertyRemoteAllowedShippingMethods()
    {
    }

    /**
     * Test attribute "shipping_cost"
     */
    public function testPropertyShippingCost()
    {
    }

    /**
     * Test attribute "shipment_increment_id"
     */
    public function testPropertyShipmentIncrementId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "seller_email"
     */
    public function testPropertySellerEmail()
    {
    }

    /**
     * Test attribute "latest_ship_date"
     */
    public function testPropertyLatestShipDate()
    {
    }

    /**
     * Test attribute "is_prime"
     */
    public function testPropertyIsPrime()
    {
    }

    /**
     * Test attribute "store_id"
     */
    public function testPropertyStoreId()
    {
    }

    /**
     * Test attribute "order_no"
     */
    public function testPropertyOrderNo()
    {
    }

    /**
     * Test attribute "purchased_order_number"
     */
    public function testPropertyPurchasedOrderNumber()
    {
    }

    /**
     * Test attribute "earliest_ship_date"
     */
    public function testPropertyEarliestShipDate()
    {
    }

    /**
     * Test attribute "shipment_service_level_category"
     */
    public function testPropertyShipmentServiceLevelCategory()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "tracking_number_id"
     */
    public function testPropertyTrackingNumberId()
    {
    }

    /**
     * Test attribute "comment_merchant"
     */
    public function testPropertyCommentMerchant()
    {
    }

    /**
     * Test attribute "order_id"
     */
    public function testPropertyOrderId()
    {
    }

    /**
     * Test attribute "ship_service_level"
     */
    public function testPropertyShipServiceLevel()
    {
    }

    /**
     * Test attribute "number_of_items_shipped"
     */
    public function testPropertyNumberOfItemsShipped()
    {
    }

    /**
     * Test attribute "shipment_method"
     */
    public function testPropertyShipmentMethod()
    {
    }

    /**
     * Test attribute "buyer_id"
     */
    public function testPropertyBuyerId()
    {
    }

    /**
     * Test attribute "pretax_total"
     */
    public function testPropertyPretaxTotal()
    {
    }

    /**
     * Test attribute "date_paid"
     */
    public function testPropertyDatePaid()
    {
    }

    /**
     * Test attribute "invoice_address_id"
     */
    public function testPropertyInvoiceAddressId()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "date_approved"
     */
    public function testPropertyDateApproved()
    {
    }

    /**
     * Test attribute "shipping_address_id"
     */
    public function testPropertyShippingAddressId()
    {
    }

    /**
     * Test attribute "shipment_offers_available"
     */
    public function testPropertyShipmentOffersAvailable()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "comment_client"
     */
    public function testPropertyCommentClient()
    {
    }

    /**
     * Test attribute "is_pickup"
     */
    public function testPropertyIsPickup()
    {
    }

    /**
     * Test attribute "shipment_offer_ids"
     */
    public function testPropertyShipmentOfferIds()
    {
    }

    /**
     * Test attribute "aftertax_total"
     */
    public function testPropertyAftertaxTotal()
    {
    }

    /**
     * Test attribute "increment_id"
     */
    public function testPropertyIncrementId()
    {
    }

    /**
     * Test attribute "date_cancelled"
     */
    public function testPropertyDateCancelled()
    {
    }

    /**
     * Test attribute "refund_requested"
     */
    public function testPropertyRefundRequested()
    {
    }
}
