<?php
/**
 * Listing
 *
 * PHP version 5
 *
 * @category Class
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * UnifysellApi
 *
 * The unified endpoint to eCommerce APIs.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: info@unifysell.de
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Unifysell\SDK\Model;

use \ArrayAccess;
use \Unifysell\SDK\ObjectSerializer;

/**
 * Listing Class Doc Comment
 *
 * @category Class
 * @description Listing object schema.
 * @package  Unifysell\SDK
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Listing implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Listing';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'article_current_price' => '\Unifysell\SDK\Model\Money',
        'article_id' => 'string',
        'asin' => 'string',
        'asin1' => 'string',
        'asin2' => 'string',
        'asin3' => 'string',
        'auction_id' => 'string',
        'auction_mode_id' => 'string',
        'baseprice_unit' => 'string',
        'baseprice_volume' => 'float',
        'buy_now_price' => '\Unifysell\SDK\Model\Money',
        'category_ids' => 'int[]',
        'comment' => 'string',
        'cross_selling_title' => 'string',
        'date_changed' => 'string',
        'date_created' => 'string',
        'date_finished' => 'string',
        'date_quantity_changed' => 'string',
        'date_started' => 'string',
        'delivery' => 'string',
        'description' => 'string',
        'ean' => 'string',
        'ebay_item_id' => 'string',
        'has_variants' => 'bool',
        'id' => 'int',
        'id_type' => 'string',
        'inci' => 'string',
        'increment' => 'float',
        'is_available' => 'bool',
        'is_closed' => 'bool',
        'is_connect' => 'bool',
        'is_planned' => 'bool',
        'is_shown_on_homepage' => 'bool',
        'is_stock_policed' => 'bool',
        'is_visible' => 'bool',
        'isbn' => 'string',
        'language_id' => 'string',
        'listing_id' => 'string',
        'marketplace_id' => 'int',
        'min_order_qty' => 'int',
        'minimum_bid_price' => '\Unifysell\SDK\Model\Money',
        'mpn' => 'string',
        'note' => 'string',
        'platform_sku' => 'string',
        'price' => '\Unifysell\SDK\Model\Money',
        'price_reduced' => '\Unifysell\SDK\Model\Money',
        'price_reduced_type' => 'string',
        'producer' => 'string',
        'product_id' => 'string',
        'qty_date' => 'string',
        'qty_old' => 'int',
        'qty_processed' => 'int',
        'quantity' => 'int',
        'rakuten_category_id' => 'string',
        'seller_sku' => 'string',
        'set_id' => 'string',
        'shipping_group' => 'int',
        'shop_category_id' => 'string',
        'staggering' => 'string',
        'start_price' => '\Unifysell\SDK\Model\Money',
        'status' => 'string',
        'tax' => 'float',
        'title' => 'string',
        'type' => 'string',
        'upc' => 'string',
        'url' => 'string',
        'url_marketing' => 'string',
        'url_portal' => 'string',
        'url_shop' => 'string',
        'watch_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'article_current_price' => null,
        'article_id' => null,
        'asin' => null,
        'asin1' => null,
        'asin2' => null,
        'asin3' => null,
        'auction_id' => null,
        'auction_mode_id' => null,
        'baseprice_unit' => null,
        'baseprice_volume' => 'float',
        'buy_now_price' => null,
        'category_ids' => null,
        'comment' => null,
        'cross_selling_title' => null,
        'date_changed' => 'datetime',
        'date_created' => 'datetime',
        'date_finished' => 'datetime',
        'date_quantity_changed' => 'datetime',
        'date_started' => 'datetime',
        'delivery' => null,
        'description' => null,
        'ean' => null,
        'ebay_item_id' => null,
        'has_variants' => null,
        'id' => null,
        'id_type' => null,
        'inci' => null,
        'increment' => 'float',
        'is_available' => null,
        'is_closed' => null,
        'is_connect' => null,
        'is_planned' => null,
        'is_shown_on_homepage' => null,
        'is_stock_policed' => null,
        'is_visible' => null,
        'isbn' => null,
        'language_id' => null,
        'listing_id' => null,
        'marketplace_id' => null,
        'min_order_qty' => null,
        'minimum_bid_price' => null,
        'mpn' => null,
        'note' => null,
        'platform_sku' => null,
        'price' => null,
        'price_reduced' => null,
        'price_reduced_type' => null,
        'producer' => null,
        'product_id' => null,
        'qty_date' => 'datetime',
        'qty_old' => null,
        'qty_processed' => null,
        'quantity' => null,
        'rakuten_category_id' => null,
        'seller_sku' => null,
        'set_id' => null,
        'shipping_group' => null,
        'shop_category_id' => null,
        'staggering' => null,
        'start_price' => null,
        'status' => null,
        'tax' => 'float',
        'title' => null,
        'type' => null,
        'upc' => null,
        'url' => null,
        'url_marketing' => null,
        'url_portal' => null,
        'url_shop' => null,
        'watch_count' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'article_current_price' => 'articleCurrentPrice',
        'article_id' => 'articleId',
        'asin' => 'asin',
        'asin1' => 'asin1',
        'asin2' => 'asin2',
        'asin3' => 'asin3',
        'auction_id' => 'auctionId',
        'auction_mode_id' => 'auctionModeId',
        'baseprice_unit' => 'basepriceUnit',
        'baseprice_volume' => 'basepriceVolume',
        'buy_now_price' => 'buyNowPrice',
        'category_ids' => 'categoryIds',
        'comment' => 'comment',
        'cross_selling_title' => 'crossSellingTitle',
        'date_changed' => 'dateChanged',
        'date_created' => 'dateCreated',
        'date_finished' => 'dateFinished',
        'date_quantity_changed' => 'dateQuantityChanged',
        'date_started' => 'dateStarted',
        'delivery' => 'delivery',
        'description' => 'description',
        'ean' => 'ean',
        'ebay_item_id' => 'ebayItemId',
        'has_variants' => 'hasVariants',
        'id' => 'id',
        'id_type' => 'idType',
        'inci' => 'inci',
        'increment' => 'increment',
        'is_available' => 'isAvailable',
        'is_closed' => 'isClosed',
        'is_connect' => 'isConnect',
        'is_planned' => 'isPlanned',
        'is_shown_on_homepage' => 'isShownOnHomepage',
        'is_stock_policed' => 'isStockPoliced',
        'is_visible' => 'isVisible',
        'isbn' => 'isbn',
        'language_id' => 'languageId',
        'listing_id' => 'listingId',
        'marketplace_id' => 'marketplaceId',
        'min_order_qty' => 'minOrderQty',
        'minimum_bid_price' => 'minimumBidPrice',
        'mpn' => 'mpn',
        'note' => 'note',
        'platform_sku' => 'platformSku',
        'price' => 'price',
        'price_reduced' => 'priceReduced',
        'price_reduced_type' => 'priceReducedType',
        'producer' => 'producer',
        'product_id' => 'productId',
        'qty_date' => 'qtyDate',
        'qty_old' => 'qtyOld',
        'qty_processed' => 'qtyProcessed',
        'quantity' => 'quantity',
        'rakuten_category_id' => 'rakutenCategoryId',
        'seller_sku' => 'sellerSku',
        'set_id' => 'setId',
        'shipping_group' => 'shippingGroup',
        'shop_category_id' => 'shopCategoryId',
        'staggering' => 'staggering',
        'start_price' => 'startPrice',
        'status' => 'status',
        'tax' => 'tax',
        'title' => 'title',
        'type' => 'type',
        'upc' => 'upc',
        'url' => 'url',
        'url_marketing' => 'urlMarketing',
        'url_portal' => 'urlPortal',
        'url_shop' => 'urlShop',
        'watch_count' => 'watchCount'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'article_current_price' => 'setArticleCurrentPrice',
        'article_id' => 'setArticleId',
        'asin' => 'setAsin',
        'asin1' => 'setAsin1',
        'asin2' => 'setAsin2',
        'asin3' => 'setAsin3',
        'auction_id' => 'setAuctionId',
        'auction_mode_id' => 'setAuctionModeId',
        'baseprice_unit' => 'setBasepriceUnit',
        'baseprice_volume' => 'setBasepriceVolume',
        'buy_now_price' => 'setBuyNowPrice',
        'category_ids' => 'setCategoryIds',
        'comment' => 'setComment',
        'cross_selling_title' => 'setCrossSellingTitle',
        'date_changed' => 'setDateChanged',
        'date_created' => 'setDateCreated',
        'date_finished' => 'setDateFinished',
        'date_quantity_changed' => 'setDateQuantityChanged',
        'date_started' => 'setDateStarted',
        'delivery' => 'setDelivery',
        'description' => 'setDescription',
        'ean' => 'setEan',
        'ebay_item_id' => 'setEbayItemId',
        'has_variants' => 'setHasVariants',
        'id' => 'setId',
        'id_type' => 'setIdType',
        'inci' => 'setInci',
        'increment' => 'setIncrement',
        'is_available' => 'setIsAvailable',
        'is_closed' => 'setIsClosed',
        'is_connect' => 'setIsConnect',
        'is_planned' => 'setIsPlanned',
        'is_shown_on_homepage' => 'setIsShownOnHomepage',
        'is_stock_policed' => 'setIsStockPoliced',
        'is_visible' => 'setIsVisible',
        'isbn' => 'setIsbn',
        'language_id' => 'setLanguageId',
        'listing_id' => 'setListingId',
        'marketplace_id' => 'setMarketplaceId',
        'min_order_qty' => 'setMinOrderQty',
        'minimum_bid_price' => 'setMinimumBidPrice',
        'mpn' => 'setMpn',
        'note' => 'setNote',
        'platform_sku' => 'setPlatformSku',
        'price' => 'setPrice',
        'price_reduced' => 'setPriceReduced',
        'price_reduced_type' => 'setPriceReducedType',
        'producer' => 'setProducer',
        'product_id' => 'setProductId',
        'qty_date' => 'setQtyDate',
        'qty_old' => 'setQtyOld',
        'qty_processed' => 'setQtyProcessed',
        'quantity' => 'setQuantity',
        'rakuten_category_id' => 'setRakutenCategoryId',
        'seller_sku' => 'setSellerSku',
        'set_id' => 'setSetId',
        'shipping_group' => 'setShippingGroup',
        'shop_category_id' => 'setShopCategoryId',
        'staggering' => 'setStaggering',
        'start_price' => 'setStartPrice',
        'status' => 'setStatus',
        'tax' => 'setTax',
        'title' => 'setTitle',
        'type' => 'setType',
        'upc' => 'setUpc',
        'url' => 'setUrl',
        'url_marketing' => 'setUrlMarketing',
        'url_portal' => 'setUrlPortal',
        'url_shop' => 'setUrlShop',
        'watch_count' => 'setWatchCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'article_current_price' => 'getArticleCurrentPrice',
        'article_id' => 'getArticleId',
        'asin' => 'getAsin',
        'asin1' => 'getAsin1',
        'asin2' => 'getAsin2',
        'asin3' => 'getAsin3',
        'auction_id' => 'getAuctionId',
        'auction_mode_id' => 'getAuctionModeId',
        'baseprice_unit' => 'getBasepriceUnit',
        'baseprice_volume' => 'getBasepriceVolume',
        'buy_now_price' => 'getBuyNowPrice',
        'category_ids' => 'getCategoryIds',
        'comment' => 'getComment',
        'cross_selling_title' => 'getCrossSellingTitle',
        'date_changed' => 'getDateChanged',
        'date_created' => 'getDateCreated',
        'date_finished' => 'getDateFinished',
        'date_quantity_changed' => 'getDateQuantityChanged',
        'date_started' => 'getDateStarted',
        'delivery' => 'getDelivery',
        'description' => 'getDescription',
        'ean' => 'getEan',
        'ebay_item_id' => 'getEbayItemId',
        'has_variants' => 'getHasVariants',
        'id' => 'getId',
        'id_type' => 'getIdType',
        'inci' => 'getInci',
        'increment' => 'getIncrement',
        'is_available' => 'getIsAvailable',
        'is_closed' => 'getIsClosed',
        'is_connect' => 'getIsConnect',
        'is_planned' => 'getIsPlanned',
        'is_shown_on_homepage' => 'getIsShownOnHomepage',
        'is_stock_policed' => 'getIsStockPoliced',
        'is_visible' => 'getIsVisible',
        'isbn' => 'getIsbn',
        'language_id' => 'getLanguageId',
        'listing_id' => 'getListingId',
        'marketplace_id' => 'getMarketplaceId',
        'min_order_qty' => 'getMinOrderQty',
        'minimum_bid_price' => 'getMinimumBidPrice',
        'mpn' => 'getMpn',
        'note' => 'getNote',
        'platform_sku' => 'getPlatformSku',
        'price' => 'getPrice',
        'price_reduced' => 'getPriceReduced',
        'price_reduced_type' => 'getPriceReducedType',
        'producer' => 'getProducer',
        'product_id' => 'getProductId',
        'qty_date' => 'getQtyDate',
        'qty_old' => 'getQtyOld',
        'qty_processed' => 'getQtyProcessed',
        'quantity' => 'getQuantity',
        'rakuten_category_id' => 'getRakutenCategoryId',
        'seller_sku' => 'getSellerSku',
        'set_id' => 'getSetId',
        'shipping_group' => 'getShippingGroup',
        'shop_category_id' => 'getShopCategoryId',
        'staggering' => 'getStaggering',
        'start_price' => 'getStartPrice',
        'status' => 'getStatus',
        'tax' => 'getTax',
        'title' => 'getTitle',
        'type' => 'getType',
        'upc' => 'getUpc',
        'url' => 'getUrl',
        'url_marketing' => 'getUrlMarketing',
        'url_portal' => 'getUrlPortal',
        'url_shop' => 'getUrlShop',
        'watch_count' => 'getWatchCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['article_current_price'] = isset($data['article_current_price']) ? $data['article_current_price'] : null;
        $this->container['article_id'] = isset($data['article_id']) ? $data['article_id'] : null;
        $this->container['asin'] = isset($data['asin']) ? $data['asin'] : null;
        $this->container['asin1'] = isset($data['asin1']) ? $data['asin1'] : null;
        $this->container['asin2'] = isset($data['asin2']) ? $data['asin2'] : null;
        $this->container['asin3'] = isset($data['asin3']) ? $data['asin3'] : null;
        $this->container['auction_id'] = isset($data['auction_id']) ? $data['auction_id'] : null;
        $this->container['auction_mode_id'] = isset($data['auction_mode_id']) ? $data['auction_mode_id'] : null;
        $this->container['baseprice_unit'] = isset($data['baseprice_unit']) ? $data['baseprice_unit'] : null;
        $this->container['baseprice_volume'] = isset($data['baseprice_volume']) ? $data['baseprice_volume'] : null;
        $this->container['buy_now_price'] = isset($data['buy_now_price']) ? $data['buy_now_price'] : null;
        $this->container['category_ids'] = isset($data['category_ids']) ? $data['category_ids'] : null;
        $this->container['comment'] = isset($data['comment']) ? $data['comment'] : null;
        $this->container['cross_selling_title'] = isset($data['cross_selling_title']) ? $data['cross_selling_title'] : null;
        $this->container['date_changed'] = isset($data['date_changed']) ? $data['date_changed'] : null;
        $this->container['date_created'] = isset($data['date_created']) ? $data['date_created'] : null;
        $this->container['date_finished'] = isset($data['date_finished']) ? $data['date_finished'] : null;
        $this->container['date_quantity_changed'] = isset($data['date_quantity_changed']) ? $data['date_quantity_changed'] : null;
        $this->container['date_started'] = isset($data['date_started']) ? $data['date_started'] : null;
        $this->container['delivery'] = isset($data['delivery']) ? $data['delivery'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['ean'] = isset($data['ean']) ? $data['ean'] : null;
        $this->container['ebay_item_id'] = isset($data['ebay_item_id']) ? $data['ebay_item_id'] : null;
        $this->container['has_variants'] = isset($data['has_variants']) ? $data['has_variants'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['id_type'] = isset($data['id_type']) ? $data['id_type'] : null;
        $this->container['inci'] = isset($data['inci']) ? $data['inci'] : null;
        $this->container['increment'] = isset($data['increment']) ? $data['increment'] : null;
        $this->container['is_available'] = isset($data['is_available']) ? $data['is_available'] : null;
        $this->container['is_closed'] = isset($data['is_closed']) ? $data['is_closed'] : null;
        $this->container['is_connect'] = isset($data['is_connect']) ? $data['is_connect'] : null;
        $this->container['is_planned'] = isset($data['is_planned']) ? $data['is_planned'] : null;
        $this->container['is_shown_on_homepage'] = isset($data['is_shown_on_homepage']) ? $data['is_shown_on_homepage'] : null;
        $this->container['is_stock_policed'] = isset($data['is_stock_policed']) ? $data['is_stock_policed'] : null;
        $this->container['is_visible'] = isset($data['is_visible']) ? $data['is_visible'] : null;
        $this->container['isbn'] = isset($data['isbn']) ? $data['isbn'] : null;
        $this->container['language_id'] = isset($data['language_id']) ? $data['language_id'] : null;
        $this->container['listing_id'] = isset($data['listing_id']) ? $data['listing_id'] : null;
        $this->container['marketplace_id'] = isset($data['marketplace_id']) ? $data['marketplace_id'] : null;
        $this->container['min_order_qty'] = isset($data['min_order_qty']) ? $data['min_order_qty'] : null;
        $this->container['minimum_bid_price'] = isset($data['minimum_bid_price']) ? $data['minimum_bid_price'] : null;
        $this->container['mpn'] = isset($data['mpn']) ? $data['mpn'] : null;
        $this->container['note'] = isset($data['note']) ? $data['note'] : null;
        $this->container['platform_sku'] = isset($data['platform_sku']) ? $data['platform_sku'] : null;
        $this->container['price'] = isset($data['price']) ? $data['price'] : null;
        $this->container['price_reduced'] = isset($data['price_reduced']) ? $data['price_reduced'] : null;
        $this->container['price_reduced_type'] = isset($data['price_reduced_type']) ? $data['price_reduced_type'] : null;
        $this->container['producer'] = isset($data['producer']) ? $data['producer'] : null;
        $this->container['product_id'] = isset($data['product_id']) ? $data['product_id'] : null;
        $this->container['qty_date'] = isset($data['qty_date']) ? $data['qty_date'] : null;
        $this->container['qty_old'] = isset($data['qty_old']) ? $data['qty_old'] : null;
        $this->container['qty_processed'] = isset($data['qty_processed']) ? $data['qty_processed'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['rakuten_category_id'] = isset($data['rakuten_category_id']) ? $data['rakuten_category_id'] : null;
        $this->container['seller_sku'] = isset($data['seller_sku']) ? $data['seller_sku'] : null;
        $this->container['set_id'] = isset($data['set_id']) ? $data['set_id'] : null;
        $this->container['shipping_group'] = isset($data['shipping_group']) ? $data['shipping_group'] : null;
        $this->container['shop_category_id'] = isset($data['shop_category_id']) ? $data['shop_category_id'] : null;
        $this->container['staggering'] = isset($data['staggering']) ? $data['staggering'] : null;
        $this->container['start_price'] = isset($data['start_price']) ? $data['start_price'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['tax'] = isset($data['tax']) ? $data['tax'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['upc'] = isset($data['upc']) ? $data['upc'] : null;
        $this->container['url'] = isset($data['url']) ? $data['url'] : null;
        $this->container['url_marketing'] = isset($data['url_marketing']) ? $data['url_marketing'] : null;
        $this->container['url_portal'] = isset($data['url_portal']) ? $data['url_portal'] : null;
        $this->container['url_shop'] = isset($data['url_shop']) ? $data['url_shop'] : null;
        $this->container['watch_count'] = isset($data['watch_count']) ? $data['watch_count'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets article_current_price
     *
     * @return \Unifysell\SDK\Model\Money
     */
    public function getArticleCurrentPrice()
    {
        return $this->container['article_current_price'];
    }

    /**
     * Sets article_current_price
     *
     * @param \Unifysell\SDK\Model\Money $article_current_price article_current_price
     *
     * @return $this
     */
    public function setArticleCurrentPrice($article_current_price)
    {
        $this->container['article_current_price'] = $article_current_price;

        return $this;
    }

    /**
     * Gets article_id
     *
     * @return string
     */
    public function getArticleId()
    {
        return $this->container['article_id'];
    }

    /**
     * Sets article_id
     *
     * @param string $article_id A unique identifier of the listing on ricardo.
     *
     * @return $this
     */
    public function setArticleId($article_id)
    {
        $this->container['article_id'] = $article_id;

        return $this;
    }

    /**
     * Gets asin
     *
     * @return string
     */
    public function getAsin()
    {
        return $this->container['asin'];
    }

    /**
     * Sets asin
     *
     * @param string $asin An asin of the listing. Set on amazon.
     *
     * @return $this
     */
    public function setAsin($asin)
    {
        $this->container['asin'] = $asin;

        return $this;
    }

    /**
     * Gets asin1
     *
     * @return string
     */
    public function getAsin1()
    {
        return $this->container['asin1'];
    }

    /**
     * Sets asin1
     *
     * @param string $asin1 An asin of the listing. Set on amazon.
     *
     * @return $this
     */
    public function setAsin1($asin1)
    {
        $this->container['asin1'] = $asin1;

        return $this;
    }

    /**
     * Gets asin2
     *
     * @return string
     */
    public function getAsin2()
    {
        return $this->container['asin2'];
    }

    /**
     * Sets asin2
     *
     * @param string $asin2 An asin of the listing. Set on amazon.
     *
     * @return $this
     */
    public function setAsin2($asin2)
    {
        $this->container['asin2'] = $asin2;

        return $this;
    }

    /**
     * Gets asin3
     *
     * @return string
     */
    public function getAsin3()
    {
        return $this->container['asin3'];
    }

    /**
     * Sets asin3
     *
     * @param string $asin3 An asin of the listing. Set on amazon.
     *
     * @return $this
     */
    public function setAsin3($asin3)
    {
        $this->container['asin3'] = $asin3;

        return $this;
    }

    /**
     * Gets auction_id
     *
     * @return string
     */
    public function getAuctionId()
    {
        return $this->container['auction_id'];
    }

    /**
     * Sets auction_id
     *
     * @param string $auction_id Hoods internal listing identifier.
     *
     * @return $this
     */
    public function setAuctionId($auction_id)
    {
        $this->container['auction_id'] = $auction_id;

        return $this;
    }

    /**
     * Gets auction_mode_id
     *
     * @return string
     */
    public function getAuctionModeId()
    {
        return $this->container['auction_mode_id'];
    }

    /**
     * Sets auction_mode_id
     *
     * @param string $auction_mode_id Defines the auction mode set on a hood listing.
     *
     * @return $this
     */
    public function setAuctionModeId($auction_mode_id)
    {
        $this->container['auction_mode_id'] = $auction_mode_id;

        return $this;
    }

    /**
     * Gets baseprice_unit
     *
     * @return string
     */
    public function getBasepriceUnit()
    {
        return $this->container['baseprice_unit'];
    }

    /**
     * Sets baseprice_unit
     *
     * @param string $baseprice_unit Gives the unit of the price property on rakuten.
     *
     * @return $this
     */
    public function setBasepriceUnit($baseprice_unit)
    {
        $this->container['baseprice_unit'] = $baseprice_unit;

        return $this;
    }

    /**
     * Gets baseprice_volume
     *
     * @return float
     */
    public function getBasepriceVolume()
    {
        return $this->container['baseprice_volume'];
    }

    /**
     * Sets baseprice_volume
     *
     * @param float $baseprice_volume The volume of the base price on rakuten.
     *
     * @return $this
     */
    public function setBasepriceVolume($baseprice_volume)
    {
        $this->container['baseprice_volume'] = $baseprice_volume;

        return $this;
    }

    /**
     * Gets buy_now_price
     *
     * @return \Unifysell\SDK\Model\Money
     */
    public function getBuyNowPrice()
    {
        return $this->container['buy_now_price'];
    }

    /**
     * Sets buy_now_price
     *
     * @param \Unifysell\SDK\Model\Money $buy_now_price buy_now_price
     *
     * @return $this
     */
    public function setBuyNowPrice($buy_now_price)
    {
        $this->container['buy_now_price'] = $buy_now_price;

        return $this;
    }

    /**
     * Gets category_ids
     *
     * @return int[]
     */
    public function getCategoryIds()
    {
        return $this->container['category_ids'];
    }

    /**
     * Sets category_ids
     *
     * @param int[] $category_ids A list of category ids the listing is part of.
     *
     * @return $this
     */
    public function setCategoryIds($category_ids)
    {
        $this->container['category_ids'] = $category_ids;

        return $this;
    }

    /**
     * Gets comment
     *
     * @return string
     */
    public function getComment()
    {
        return $this->container['comment'];
    }

    /**
     * Sets comment
     *
     * @param string $comment A listing comment on rakuten.
     *
     * @return $this
     */
    public function setComment($comment)
    {
        $this->container['comment'] = $comment;

        return $this;
    }

    /**
     * Gets cross_selling_title
     *
     * @return string
     */
    public function getCrossSellingTitle()
    {
        return $this->container['cross_selling_title'];
    }

    /**
     * Sets cross_selling_title
     *
     * @param string $cross_selling_title The listings title for rakuten cross selling.
     *
     * @return $this
     */
    public function setCrossSellingTitle($cross_selling_title)
    {
        $this->container['cross_selling_title'] = $cross_selling_title;

        return $this;
    }

    /**
     * Gets date_changed
     *
     * @return string
     */
    public function getDateChanged()
    {
        return $this->container['date_changed'];
    }

    /**
     * Sets date_changed
     *
     * @param string $date_changed Timestamp of the latest update to the listing.
     *
     * @return $this
     */
    public function setDateChanged($date_changed)
    {
        $this->container['date_changed'] = $date_changed;

        return $this;
    }

    /**
     * Gets date_created
     *
     * @return string
     */
    public function getDateCreated()
    {
        return $this->container['date_created'];
    }

    /**
     * Sets date_created
     *
     * @param string $date_created Timestamp of creation of the listing.
     *
     * @return $this
     */
    public function setDateCreated($date_created)
    {
        $this->container['date_created'] = $date_created;

        return $this;
    }

    /**
     * Gets date_finished
     *
     * @return string
     */
    public function getDateFinished()
    {
        return $this->container['date_finished'];
    }

    /**
     * Sets date_finished
     *
     * @param string $date_finished A date that gives the end of a listings auction.
     *
     * @return $this
     */
    public function setDateFinished($date_finished)
    {
        $this->container['date_finished'] = $date_finished;

        return $this;
    }

    /**
     * Gets date_quantity_changed
     *
     * @return string
     */
    public function getDateQuantityChanged()
    {
        return $this->container['date_quantity_changed'];
    }

    /**
     * Sets date_quantity_changed
     *
     * @param string $date_quantity_changed The timestamp when the quantity was changed last.
     *
     * @return $this
     */
    public function setDateQuantityChanged($date_quantity_changed)
    {
        $this->container['date_quantity_changed'] = $date_quantity_changed;

        return $this;
    }

    /**
     * Gets date_started
     *
     * @return string
     */
    public function getDateStarted()
    {
        return $this->container['date_started'];
    }

    /**
     * Sets date_started
     *
     * @param string $date_started A date that gives the start of a listings auction.
     *
     * @return $this
     */
    public function setDateStarted($date_started)
    {
        $this->container['date_started'] = $date_started;

        return $this;
    }

    /**
     * Gets delivery
     *
     * @return string
     */
    public function getDelivery()
    {
        return $this->container['delivery'];
    }

    /**
     * Sets delivery
     *
     * @param string $delivery The delivery options chosen for the listing.
     *
     * @return $this
     */
    public function setDelivery($delivery)
    {
        $this->container['delivery'] = $delivery;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description Describes the listing and the related product to be sold.
     *
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets ean
     *
     * @return string
     */
    public function getEan()
    {
        return $this->container['ean'];
    }

    /**
     * Sets ean
     *
     * @param string $ean International Article Number / European Article Number.
     *
     * @return $this
     */
    public function setEan($ean)
    {
        $this->container['ean'] = $ean;

        return $this;
    }

    /**
     * Gets ebay_item_id
     *
     * @return string
     */
    public function getEbayItemId()
    {
        return $this->container['ebay_item_id'];
    }

    /**
     * Sets ebay_item_id
     *
     * @param string $ebay_item_id Ebays internal listing identifier.
     *
     * @return $this
     */
    public function setEbayItemId($ebay_item_id)
    {
        $this->container['ebay_item_id'] = $ebay_item_id;

        return $this;
    }

    /**
     * Gets has_variants
     *
     * @return bool
     */
    public function getHasVariants()
    {
        return $this->container['has_variants'];
    }

    /**
     * Sets has_variants
     *
     * @param bool $has_variants Tells if the listing has variants on rakuten.
     *
     * @return $this
     */
    public function setHasVariants($has_variants)
    {
        $this->container['has_variants'] = $has_variants;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id The unique identifier.
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets id_type
     *
     * @return string
     */
    public function getIdType()
    {
        return $this->container['id_type'];
    }

    /**
     * Sets id_type
     *
     * @param string $id_type The idType of the listing on amazon.
     *
     * @return $this
     */
    public function setIdType($id_type)
    {
        $this->container['id_type'] = $id_type;

        return $this;
    }

    /**
     * Gets inci
     *
     * @return string
     */
    public function getInci()
    {
        return $this->container['inci'];
    }

    /**
     * Sets inci
     *
     * @param string $inci The inci identifier of a listing on rakuten.
     *
     * @return $this
     */
    public function setInci($inci)
    {
        $this->container['inci'] = $inci;

        return $this;
    }

    /**
     * Gets increment
     *
     * @return float
     */
    public function getIncrement()
    {
        return $this->container['increment'];
    }

    /**
     * Sets increment
     *
     * @param float $increment The incremental step for an auction bid on ricardo.
     *
     * @return $this
     */
    public function setIncrement($increment)
    {
        $this->container['increment'] = $increment;

        return $this;
    }

    /**
     * Gets is_available
     *
     * @return bool
     */
    public function getIsAvailable()
    {
        return $this->container['is_available'];
    }

    /**
     * Sets is_available
     *
     * @param bool $is_available Defines if an rakuten listing is available.
     *
     * @return $this
     */
    public function setIsAvailable($is_available)
    {
        $this->container['is_available'] = $is_available;

        return $this;
    }

    /**
     * Gets is_closed
     *
     * @return bool
     */
    public function getIsClosed()
    {
        return $this->container['is_closed'];
    }

    /**
     * Sets is_closed
     *
     * @param bool $is_closed Defines wether a ricardo listing has been closed.
     *
     * @return $this
     */
    public function setIsClosed($is_closed)
    {
        $this->container['is_closed'] = $is_closed;

        return $this;
    }

    /**
     * Gets is_connect
     *
     * @return bool
     */
    public function getIsConnect()
    {
        return $this->container['is_connect'];
    }

    /**
     * Sets is_connect
     *
     * @param bool $is_connect Defines wether isConnect service is enabled.
     *
     * @return $this
     */
    public function setIsConnect($is_connect)
    {
        $this->container['is_connect'] = $is_connect;

        return $this;
    }

    /**
     * Gets is_planned
     *
     * @return bool
     */
    public function getIsPlanned()
    {
        return $this->container['is_planned'];
    }

    /**
     * Sets is_planned
     *
     * @param bool $is_planned Defines wether a ricardo listing is just planned yet.
     *
     * @return $this
     */
    public function setIsPlanned($is_planned)
    {
        $this->container['is_planned'] = $is_planned;

        return $this;
    }

    /**
     * Gets is_shown_on_homepage
     *
     * @return bool
     */
    public function getIsShownOnHomepage()
    {
        return $this->container['is_shown_on_homepage'];
    }

    /**
     * Sets is_shown_on_homepage
     *
     * @param bool $is_shown_on_homepage Defines if the listing is shown on the homepage on rakuten.
     *
     * @return $this
     */
    public function setIsShownOnHomepage($is_shown_on_homepage)
    {
        $this->container['is_shown_on_homepage'] = $is_shown_on_homepage;

        return $this;
    }

    /**
     * Gets is_stock_policed
     *
     * @return bool
     */
    public function getIsStockPoliced()
    {
        return $this->container['is_stock_policed'];
    }

    /**
     * Sets is_stock_policed
     *
     * @param bool $is_stock_policed Defines wether the rakuten stock policy is enabled.
     *
     * @return $this
     */
    public function setIsStockPoliced($is_stock_policed)
    {
        $this->container['is_stock_policed'] = $is_stock_policed;

        return $this;
    }

    /**
     * Gets is_visible
     *
     * @return bool
     */
    public function getIsVisible()
    {
        return $this->container['is_visible'];
    }

    /**
     * Sets is_visible
     *
     * @param bool $is_visible Defines if the listing is visible on rakuten.
     *
     * @return $this
     */
    public function setIsVisible($is_visible)
    {
        $this->container['is_visible'] = $is_visible;

        return $this;
    }

    /**
     * Gets isbn
     *
     * @return string
     */
    public function getIsbn()
    {
        return $this->container['isbn'];
    }

    /**
     * Sets isbn
     *
     * @param string $isbn The isbn number of the listings product.
     *
     * @return $this
     */
    public function setIsbn($isbn)
    {
        $this->container['isbn'] = $isbn;

        return $this;
    }

    /**
     * Gets language_id
     *
     * @return string
     */
    public function getLanguageId()
    {
        return $this->container['language_id'];
    }

    /**
     * Sets language_id
     *
     * @param string $language_id The id of language of the listing on ricardo.
     *
     * @return $this
     */
    public function setLanguageId($language_id)
    {
        $this->container['language_id'] = $language_id;

        return $this;
    }

    /**
     * Gets listing_id
     *
     * @return string
     */
    public function getListingId()
    {
        return $this->container['listing_id'];
    }

    /**
     * Sets listing_id
     *
     * @param string $listing_id A unique identifier of the listing on amazon.
     *
     * @return $this
     */
    public function setListingId($listing_id)
    {
        $this->container['listing_id'] = $listing_id;

        return $this;
    }

    /**
     * Gets marketplace_id
     *
     * @return int
     */
    public function getMarketplaceId()
    {
        return $this->container['marketplace_id'];
    }

    /**
     * Sets marketplace_id
     *
     * @param int $marketplace_id The unifysell id of the marketplace the listing is available on.
     *
     * @return $this
     */
    public function setMarketplaceId($marketplace_id)
    {
        $this->container['marketplace_id'] = $marketplace_id;

        return $this;
    }

    /**
     * Gets min_order_qty
     *
     * @return int
     */
    public function getMinOrderQty()
    {
        return $this->container['min_order_qty'];
    }

    /**
     * Sets min_order_qty
     *
     * @param int $min_order_qty Gives the minimum quantity to buy at once of a rakuten listing.
     *
     * @return $this
     */
    public function setMinOrderQty($min_order_qty)
    {
        $this->container['min_order_qty'] = $min_order_qty;

        return $this;
    }

    /**
     * Gets minimum_bid_price
     *
     * @return \Unifysell\SDK\Model\Money
     */
    public function getMinimumBidPrice()
    {
        return $this->container['minimum_bid_price'];
    }

    /**
     * Sets minimum_bid_price
     *
     * @param \Unifysell\SDK\Model\Money $minimum_bid_price minimum_bid_price
     *
     * @return $this
     */
    public function setMinimumBidPrice($minimum_bid_price)
    {
        $this->container['minimum_bid_price'] = $minimum_bid_price;

        return $this;
    }

    /**
     * Gets mpn
     *
     * @return string
     */
    public function getMpn()
    {
        return $this->container['mpn'];
    }

    /**
     * Sets mpn
     *
     * @param string $mpn The mpn identifier of a listing on rakuten.
     *
     * @return $this
     */
    public function setMpn($mpn)
    {
        $this->container['mpn'] = $mpn;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note A note set to the listing of amazon.
     *
     * @return $this
     */
    public function setNote($note)
    {
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets platform_sku
     *
     * @return string
     */
    public function getPlatformSku()
    {
        return $this->container['platform_sku'];
    }

    /**
     * Sets platform_sku
     *
     * @param string $platform_sku A platform identifier of the listing.
     *
     * @return $this
     */
    public function setPlatformSku($platform_sku)
    {
        $this->container['platform_sku'] = $platform_sku;

        return $this;
    }

    /**
     * Gets price
     *
     * @return \Unifysell\SDK\Model\Money
     */
    public function getPrice()
    {
        return $this->container['price'];
    }

    /**
     * Sets price
     *
     * @param \Unifysell\SDK\Model\Money $price price
     *
     * @return $this
     */
    public function setPrice($price)
    {
        $this->container['price'] = $price;

        return $this;
    }

    /**
     * Gets price_reduced
     *
     * @return \Unifysell\SDK\Model\Money
     */
    public function getPriceReduced()
    {
        return $this->container['price_reduced'];
    }

    /**
     * Sets price_reduced
     *
     * @param \Unifysell\SDK\Model\Money $price_reduced price_reduced
     *
     * @return $this
     */
    public function setPriceReduced($price_reduced)
    {
        $this->container['price_reduced'] = $price_reduced;

        return $this;
    }

    /**
     * Gets price_reduced_type
     *
     * @return string
     */
    public function getPriceReducedType()
    {
        return $this->container['price_reduced_type'];
    }

    /**
     * Sets price_reduced_type
     *
     * @param string $price_reduced_type Defines rakutens type of a reduced listing price.
     *
     * @return $this
     */
    public function setPriceReducedType($price_reduced_type)
    {
        $this->container['price_reduced_type'] = $price_reduced_type;

        return $this;
    }

    /**
     * Gets producer
     *
     * @return string
     */
    public function getProducer()
    {
        return $this->container['producer'];
    }

    /**
     * Sets producer
     *
     * @param string $producer The producer of a rakuten listings product.
     *
     * @return $this
     */
    public function setProducer($producer)
    {
        $this->container['producer'] = $producer;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id Magentos and Rakutens internal listing identifier.
     *
     * @return $this
     */
    public function setProductId($product_id)
    {
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets qty_date
     *
     * @return string
     */
    public function getQtyDate()
    {
        return $this->container['qty_date'];
    }

    /**
     * Sets qty_date
     *
     * @param string $qty_date This timestamp gives the last quantity change on magento.
     *
     * @return $this
     */
    public function setQtyDate($qty_date)
    {
        $this->container['qty_date'] = $qty_date;

        return $this;
    }

    /**
     * Gets qty_old
     *
     * @return int
     */
    public function getQtyOld()
    {
        return $this->container['qty_old'];
    }

    /**
     * Sets qty_old
     *
     * @param int $qty_old The quantity of a listing on magento.
     *
     * @return $this
     */
    public function setQtyOld($qty_old)
    {
        $this->container['qty_old'] = $qty_old;

        return $this;
    }

    /**
     * Gets qty_processed
     *
     * @return int
     */
    public function getQtyProcessed()
    {
        return $this->container['qty_processed'];
    }

    /**
     * Sets qty_processed
     *
     * @param int $qty_processed The quantity of processed magento listings.
     *
     * @return $this
     */
    public function setQtyProcessed($qty_processed)
    {
        $this->container['qty_processed'] = $qty_processed;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity Quantity available of the listing.
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets rakuten_category_id
     *
     * @return string
     */
    public function getRakutenCategoryId()
    {
        return $this->container['rakuten_category_id'];
    }

    /**
     * Sets rakuten_category_id
     *
     * @param string $rakuten_category_id The category id of a rakuten listing. Pointing to a rakuten category.
     *
     * @return $this
     */
    public function setRakutenCategoryId($rakuten_category_id)
    {
        $this->container['rakuten_category_id'] = $rakuten_category_id;

        return $this;
    }

    /**
     * Gets seller_sku
     *
     * @return string
     */
    public function getSellerSku()
    {
        return $this->container['seller_sku'];
    }

    /**
     * Sets seller_sku
     *
     * @param string $seller_sku An amazon listing identifier given by the seller.
     *
     * @return $this
     */
    public function setSellerSku($seller_sku)
    {
        $this->container['seller_sku'] = $seller_sku;

        return $this;
    }

    /**
     * Gets set_id
     *
     * @return string
     */
    public function getSetId()
    {
        return $this->container['set_id'];
    }

    /**
     * Sets set_id
     *
     * @param string $set_id Gives the magento set of the listing.
     *
     * @return $this
     */
    public function setSetId($set_id)
    {
        $this->container['set_id'] = $set_id;

        return $this;
    }

    /**
     * Gets shipping_group
     *
     * @return int
     */
    public function getShippingGroup()
    {
        return $this->container['shipping_group'];
    }

    /**
     * Sets shipping_group
     *
     * @param int $shipping_group Gives the rakuten id of the shipping group.
     *
     * @return $this
     */
    public function setShippingGroup($shipping_group)
    {
        $this->container['shipping_group'] = $shipping_group;

        return $this;
    }

    /**
     * Gets shop_category_id
     *
     * @return string
     */
    public function getShopCategoryId()
    {
        return $this->container['shop_category_id'];
    }

    /**
     * Sets shop_category_id
     *
     * @param string $shop_category_id The category id of a rakuten listing. Pointing to a shop category.
     *
     * @return $this
     */
    public function setShopCategoryId($shop_category_id)
    {
        $this->container['shop_category_id'] = $shop_category_id;

        return $this;
    }

    /**
     * Gets staggering
     *
     * @return string
     */
    public function getStaggering()
    {
        return $this->container['staggering'];
    }

    /**
     * Sets staggering
     *
     * @param string $staggering 
     *
     * @return $this
     */
    public function setStaggering($staggering)
    {
        $this->container['staggering'] = $staggering;

        return $this;
    }

    /**
     * Gets start_price
     *
     * @return \Unifysell\SDK\Model\Money
     */
    public function getStartPrice()
    {
        return $this->container['start_price'];
    }

    /**
     * Sets start_price
     *
     * @param \Unifysell\SDK\Model\Money $start_price start_price
     *
     * @return $this
     */
    public function setStartPrice($start_price)
    {
        $this->container['start_price'] = $start_price;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The status of the listing.
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets tax
     *
     * @return float
     */
    public function getTax()
    {
        return $this->container['tax'];
    }

    /**
     * Sets tax
     *
     * @param float $tax The tax level which is applied for a listings buy.
     *
     * @return $this
     */
    public function setTax($tax)
    {
        $this->container['tax'] = $tax;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title The title of the listing.
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type The magento listing type.
     *
     * @return $this
     */
    public function setType($type)
    {
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets upc
     *
     * @return string
     */
    public function getUpc()
    {
        return $this->container['upc'];
    }

    /**
     * Sets upc
     *
     * @param string $upc The upc number of the listing.
     *
     * @return $this
     */
    public function setUpc($upc)
    {
        $this->container['upc'] = $upc;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url The url. The listing can be reached calling it.
     *
     * @return $this
     */
    public function setUrl($url)
    {
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets url_marketing
     *
     * @return string
     */
    public function getUrlMarketing()
    {
        return $this->container['url_marketing'];
    }

    /**
     * Sets url_marketing
     *
     * @param string $url_marketing The marketing url on rakuten.
     *
     * @return $this
     */
    public function setUrlMarketing($url_marketing)
    {
        $this->container['url_marketing'] = $url_marketing;

        return $this;
    }

    /**
     * Gets url_portal
     *
     * @return string
     */
    public function getUrlPortal()
    {
        return $this->container['url_portal'];
    }

    /**
     * Sets url_portal
     *
     * @param string $url_portal The url to the portal on rakuten.
     *
     * @return $this
     */
    public function setUrlPortal($url_portal)
    {
        $this->container['url_portal'] = $url_portal;

        return $this;
    }

    /**
     * Gets url_shop
     *
     * @return string
     */
    public function getUrlShop()
    {
        return $this->container['url_shop'];
    }

    /**
     * Sets url_shop
     *
     * @param string $url_shop The url to the shop on rakuten.
     *
     * @return $this
     */
    public function setUrlShop($url_shop)
    {
        $this->container['url_shop'] = $url_shop;

        return $this;
    }

    /**
     * Gets watch_count
     *
     * @return int
     */
    public function getWatchCount()
    {
        return $this->container['watch_count'];
    }

    /**
     * Sets watch_count
     *
     * @param int $watch_count Gives the number of watchers for the listing.
     *
     * @return $this
     */
    public function setWatchCount($watch_count)
    {
        $this->container['watch_count'] = $watch_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


